[package]
name = "redox-wayland-compositor"
version = "0.1.0"
edition = "2024"
authors = ["Ibuki.O <isan.ethen@gmail.com>"]

[[bin]]
name = "redox-wayland-compositor"
path = "src/main.rs"

[dependencies]
redox_syscall = "0.5"
